config/routes.rb
AndrewMitchell::Application.routes.draw do
  namespace :admin do resources :employment_history_items end

  namespace :admin do resources :educational_qualifications end

  namespace :admin do resources :categories end

  namespace :admin do resources :posts end

  namespace :admin do root :to => 'dashboard#index' end

  post        '/auth/:provider/callback'              => 'authentications#create'
  get         '/profile/connected-providers'          => 'authentications#index', :as => 'authentications'
  delete      '/profile/connected-provider/:provider' => 'authentications#destroy', :as => 'authentication'

  devise_for  :users, :controllers => { :registrations => 'registrations' }
  resources   :users


  ### FRONTEND ###

  # Static Pages
  get         '/contact'  => 'static_pages#contact'

  # About
  get         '/about'                      => 'about#index'
  get         '/employment-history'         => 'about#employment_history',          :as => 'employment_history'
  get         '/educational-qualifications' => 'about#educational_qualifications',  :as => 'educational_qualifications'

  # Comments
  resources   :comments

  # Posts
  resources   :posts, :only => [:show] do
    resources   :comments, :except => [:delete]
  end
  get         'posts/category/:category_permalink'  => 'posts#category', :as => 'posts_category'
  get         'posts/tagged/:tag'                   => 'posts#tagged'

  # Portfolio
  get '/portfolio' => 'portfolio#index'
  get '/portfolio/:id' => 'portfolio#show'
  #   resources :comments, :except => [:delete]
  # end
  # match 'portfolio/category/:category_permalink' => 'portfolio#category', :as => 'portfolio_category'
  # match 'portfolio/tagged/:tag' => 'portfolio#tagged'

  # Photos & Albums
  resources :photoalbums, :only => [:index, :show] do
    resources :pictures, :only => [:show] do
      resources :comments, :except => [:delete]
    end
  end
  match 'pictures/tagged/:tag' => 'pictures#tagged'

  root :to => "posts#index"
end

app/models/employment_history_item.rb
# == Schema Information
#
# Table name: employment_history_items
#
#  id               :integer         not null, primary key
#  company_name     :string(255)
#  company_role     :string(255)
#  role_description :text
#  date_from        :date
#  date_to          :date
#  location         :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class EmploymentHistoryItem < ActiveRecord::Base
  include Displayable

  # Attributes
  attr_accessible :company_name, :company_role, :role_description, :date_from, :date_to, :location

  validates :company_name,  :presence => true
  validates :company_role,  :presence => true
  validates :date_from,     :presence => true
end

app/controllers/admin/employment_history_items_controller.rb
class Admin::EmploymentHistoryItemsController < Admin::AdminController

  before_filter :fetch_employment_history_item,  :only => [:show, :edit, :update, :destroy]

  def index
    @employment_history_items = EmploymentHistoryItem.order('created_at DESC').paginate(:page => params[:page], :per_page => ITEMS_PER_PAGE)
  end

  def show
  end

  def new
    @employment_history_item = EmploymentHistoryItem.new
  end

  def create
    @employment_history_item = EmploymentHistoryItem.new(params[:employment_history_item])

    if @employment_history_item.save
      redirect_to admin_employment_history_item_path(@employment_history_item), :notice => "Successfully created employment history item."
    else
      render :new, :error => "Could not create employment history item. Check the errors and try again!"
    end
  end

  def edit
  end

  def update
    if @employment_history_item.update_attributes(params[:employment_history_item])
      redirect_to admin_employment_history_item_path(@employment_history_item), :notice => "Successfully updated employment history item."
    else
      render :edit, :error => "Could not update employment history item. Check the errors and try again!"
    end
  end

  def destroy
    if @employment_history_item.destroy
      flash[:notice] == "Successfully deleted employment history item."
    else
      flash[:error] == "Could not delete employment history item."
    end
    redirect_to admin_employment_history_items_path
  end

protected

  def fetch_employment_history_item
    @employment_history_item = EmploymentHistoryItem.find params[:id]
  end
end

app/views/admin/employment_history_items/_employment_history_item_mini.html.erb
<tr>
  <td><%= employment_history_item_mini.id %></td>
  <td><%= employment_history_item_mini.created_at %></td>
  <td><%= employment_history_item_mini.updated_at %></td>
  <td><%= employment_history_item_mini.company_name %></td>
  <td><%= employment_history_item_mini.company_role %></td>
  <td><%= employment_history_item_mini.role_description %></td>
  <td><%= employment_history_item_mini.date_from %></td>
  <td><%= employment_history_item_mini.date_to %></td>
  <td><%= employment_history_item_mini.location %></td>
  <td><%= link_to "Show", admin_employment_history_item_path(employment_history_item_mini) %></td>
  <td><%= link_to 'Edit', edit_admin_employment_history_item_path(employment_history_item_mini) %></td>
  <td><%= link_to 'Delete', admin_employment_history_item_path(employment_history_item_mini), :confirm => "Are you sure you want to delete this Employment history item?", :method => :delete %></td>
</tr>

app/views/admin/employment_history_items/_form.html.erb
<%= form_for [:admin, @employment_history_item], :html => { :class => "form-vertical" } do |f| %>

  <%= f.label :company_name %>
  <%= f.text_field :company_name %>
  <%= f.label :company_role %>
  <%= f.text_field :company_role %>
  <%= f.label :role_description %>
  <%= f.text_field :role_description %>
  <%= f.label :date_from %>
  <%= f.text_field :date_from %>
  <%= f.label :date_to %>
  <%= f.text_field :date_to %>
  <%= f.label :location %>
  <%= f.text_field :location %>




  <%= f.submit "Save" %>
<% end %>

app/views/admin/employment_history_items/edit.html.erb
<%= bootstrap_page_header :h1 do %>
  Edit Employment history item
  <%= bootstrap_sub_header do %>
    <%= link_to "Cancel", :back %>
  <% end %>
<% end %>

<%= render :partial => 'form' %>

app/views/admin/employment_history_items/index.html.erb
<%= bootstrap_page_header :h1 do %>
  Employment history items Admin
  <%= bootstrap_sub_header do %>
    <%= link_to "New Employment history item", new_admin_employment_history_item_path %>
  <% end %>
<% end %>

<% if @employment_history_items.empty? %>
  <p>There are currently no employment history items.</p>
<% else %>
  <table>
    <thead>
      <th>Id</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Company name</th>
      <th>Company role</th>
      <th>Role description</th>
      <th>Date from</th>
      <th>Date to</th>
      <th>Location</th>
    </thead>

    <%= render :partial => 'employment_history_item_mini', :collection => @employment_history_items %>
  </table>
<% end %>

<%= will_paginate %>

app/views/admin/employment_history_items/new.html.erb
<%= bootstrap_page_header :h1 do %>
  Create Employment history item
  <%= bootstrap_sub_header do %>
    <%= link_to "Cancel", :back %>
  <% end %>
<% end %>

<%= render :partial => 'form' %>

app/views/admin/employment_history_items/show.html.erb
<%= bootstrap_page_header :h1 do %>
  Employment history items Admin
  <%= bootstrap_sub_header do %>
    <%= link_to "Back", :back %>
  <% end %>
<% end %>

<ol>
  <li>
    <strong>Id:</strong>
    <%= @employment_history_item.display_name %>
  </li>
  <li>
    <strong>Created at:</strong>
    <%= @employment_history_item.display_name %>
  </li>
  <li>
    <strong>Updated at:</strong>
    <%= @employment_history_item.display_name %>
  </li>
  <li>
    <strong>Company name:</strong>
    <%= @employment_history_item.company_name %>
  </li>
  <li>
    <strong>Company role:</strong>
    <%= @employment_history_item.company_role %>
  </li>
  <li>
    <strong>Role description:</strong>
    <%= @employment_history_item.role_description %>
  </li>
  <li>
    <strong>Date from:</strong>
    <%= @employment_history_item.date_from %>
  </li>
  <li>
    <strong>Date to:</strong>
    <%= @employment_history_item.date_to %>
  </li>
  <li>
    <strong>Location:</strong>
    <%= @employment_history_item.location %>
  </li>
</ol>