config/routes.rb
AndrewMitchell::Application.routes.draw do
  namespace :admin do resources :employment_history_items end

  namespace :admin do resources :educational_qualifications end

  namespace :admin do resources :categories end

  namespace :admin do resources :posts end

  namespace :admin do root :to => 'dashboard#index' end

  post        '/auth/:provider/callback'              => 'authentications#create'
  get         '/profile/connected-providers'          => 'authentications#index', :as => 'authentications'
  delete      '/profile/connected-provider/:provider' => 'authentications#destroy', :as => 'authentication'

  devise_for  :users, :controllers => { :registrations => 'registrations' }
  resources   :users


  ### FRONTEND ###

  # Static Pages
  get         '/contact'  => 'static_pages#contact'

  # About
  get         '/about'                      => 'about#index'
  get         '/employment-history'         => 'about#employment_history',          :as => 'employment_history'
  get         '/educational-qualifications' => 'about#educational_qualifications',  :as => 'educational_qualifications'

  # Comments
  resources   :comments

  # Posts
  resources   :posts, :only => [:show] do
    resources   :comments, :except => [:delete]
  end
  get         'posts/category/:category_permalink'  => 'posts#category', :as => 'posts_category'
  get         'posts/tagged/:tag'                   => 'posts#tagged'

  # Portfolio
  get '/portfolio' => 'portfolio#index'
  get '/portfolio/:id' => 'portfolio#show'
  #   resources :comments, :except => [:delete]
  # end
  # match 'portfolio/category/:category_permalink' => 'portfolio#category', :as => 'portfolio_category'
  # match 'portfolio/tagged/:tag' => 'portfolio#tagged'

  # Photos & Albums
  resources :photoalbums, :only => [:index, :show] do
    resources :pictures, :only => [:show] do
      resources :comments, :except => [:delete]
    end
  end
  match 'pictures/tagged/:tag' => 'pictures#tagged'

  root :to => "posts#index"
end

app/views/shared/_available_oauth_providers.html.erb
<div class="available_oauth_providers">
  <p>Don't want to fill out all the forms? Just <%= verb %> with one of your favourite web apps:</p>
  <ul>
    <li><%= link_to image_tag("oauth_providers/twitter_64.png", :size => "64x64"), "/auth/twitter", :class => "auth_provider" %></li>
  </ul>
</div>

app/views/shared/_category_nav.html.erb
<% if @categories.any? %>
  <nav id="category_nav" class="subnav">
    <h3>Categories:</h3>
    <ul>
      <% cat1 = @categories.shift %>
      <li class="no_border"><%= link_to cat1.name, posts_category_path(cat1) %></li>
      <% @categories.each do |cat, i| %>
        <li><%= link_to cat.name, posts_category_path(cat) %></li>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/shared/_comment.html.erb
<div class="comment">
	<div class='avatar'>
    <% if comment.author.has_avatar? %>
      <%= image_tag comment.author.avatar.url(:avatar), :alt => comment.author.username %>
    <% else %>
      <%= image_tag 'blank_avatar.gif', :alt => comment.author.username %>
    <% end %>
  </div>
	<p>Posted by: <%=h comment.author.username %> on <%= comment_published_on_text(comment) %></p>
	<p><%=h comment.body %></p>
	<% if current_user && current_user.is_admin? %>
		<p>
			<%= link_to "Delete", comment_path(comment.id), :method => :delete %>
		</p>
	<% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% if flash[:error] %>
  <a id="error" name="error" href="#error" class="flash_message">
    <%= flash[:error] %>
  </a>
<% elsif flash[:alert] %>
  <a id="error" name="error" href="#error" class="flash_message">
    <%= flash[:alert] %>
  </a>
<% elsif flash[:notice] %>
  <a id="notice" name="notice" href="#notice" class="flash_message">
    <%= flash[:notice] %>
  </a>
<% end %>

app/views/shared/_form_errors.html.erb
<% if object.errors.count > 0 %>
	<div id="error_explanation">
	  <h1>Please fix the following <%= pluralize(object.errors.count, "error") %>:</h1>
	  <ul>
	    <% object.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

app/views/shared/_nav_category.html.erb
<% if @categories.any? %>
  <nav id="category_nav" class="subnav">
    <h3>Categories:</h3>
    <ul>
      <% @categories.each do |cat| %>
        <li><%= link_to cat.name, posts_category_path(cat) %></li>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/shared/_nav_social.html.erb
<% if @categories.any? %>
  <nav id="category_nav" class="subnav">
    <h3>Connect:</h3>
    <ul>
      <li><%= link_to "Twitter", "http://twitter.com/themitchelluk" %></li>
      <li><%= link_to "Github", "http://github.com/Themitchell" %></li>
      <li><%= link_to "Soundcloud", "http://soundcloud.com/themitchell" %></li>
      <li><%= link_to "LinkedIn", "http://www.linkedin.com/pub/andrew-mitchell/30/86a/b31" %></li>
    </ul>
  </nav>
<% end %>

app/views/shared/_side.html.erb
<div id="side">
	<div id="spacer"></div>
	
	<aside id="categories">
		<h2 class="side_section_title">Categories</h2>
		<ul>
		  <% if @categories.any? %>
  		  <% @categories.each do |cat| %>
  			  <li><%= link_to cat.name.titleize, posts_category_path(cat) %></li>
  			<% end %>
  		<% end %>
		</ul>
	</aside>
	
  <!-- <aside id="tags">
    <h2 class="side_section_title">Tags</h2>
    <p class="tags">All Your List Of Tags Can Go Here To Add Keywords To The Page For SEO Stuff See Look Isnt It Nice</p>
  </aside>
  
  <aside id="links">
    <h2 class="side_section_title">Useful Links</h2>
    <ul>
      <li>Link 1</li>
      <li>Link 2</li>
      <li>Link 3</li>
      <li>Link 4</li>
    </ul>
  </aside> -->
	
	<aside id="connect">
		<h2 class="side_section_title">Connect with me!</h2>
		<ul>
			<li><%= link_to image_tag('connect/twitter.gif'), "http://twitter.com/#!/themitchelluk" %></li>
			<li><%= link_to image_tag('connect/lastfm.gif'), "http://www.last.fm/user/ratherdrunk" %></li>
			<li><%= link_to image_tag('connect/linkedin.gif'), "http://uk.linkedin.com/pub/andrew-mitchell/30/86a/b31" %></li>
		</ul>
	</aside>		
</div>