config/routes.rb
AndrewMitchell::Application.routes.draw do
  namespace :admin do resources :employment_history_items end

  namespace :admin do resources :educational_qualifications end

  namespace :admin do resources :categories end

  namespace :admin do resources :posts end

  namespace :admin do root :to => 'dashboard#index' end

  post        '/auth/:provider/callback'              => 'authentications#create'
  get         '/profile/connected-providers'          => 'authentications#index', :as => 'authentications'
  delete      '/profile/connected-provider/:provider' => 'authentications#destroy', :as => 'authentication'

  devise_for  :users, :controllers => { :registrations => 'registrations' }
  resources   :users


  ### FRONTEND ###

  # Static Pages
  get         '/contact'  => 'static_pages#contact'

  # About
  get         '/about'                      => 'about#index'
  get         '/employment-history'         => 'about#employment_history',          :as => 'employment_history'
  get         '/educational-qualifications' => 'about#educational_qualifications',  :as => 'educational_qualifications'

  # Comments
  resources   :comments

  # Posts
  resources   :posts, :only => [:show] do
    resources   :comments, :except => [:delete]
  end
  get         'posts/category/:category_permalink'  => 'posts#category', :as => 'posts_category'
  get         'posts/tagged/:tag'                   => 'posts#tagged'

  # Portfolio
  get '/portfolio' => 'portfolio#index'
  get '/portfolio/:id' => 'portfolio#show'
  #   resources :comments, :except => [:delete]
  # end
  # match 'portfolio/category/:category_permalink' => 'portfolio#category', :as => 'portfolio_category'
  # match 'portfolio/tagged/:tag' => 'portfolio#tagged'

  # Photos & Albums
  resources :photoalbums, :only => [:index, :show] do
    resources :pictures, :only => [:show] do
      resources :comments, :except => [:delete]
    end
  end
  match 'pictures/tagged/:tag' => 'pictures#tagged'

  root :to => "posts#index"
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                   :integer         not null, primary key
#  title                :string(255)
#  description          :text
#  author_id            :integer
#  published_on         :datetime
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  created_at           :datetime
#  updated_at           :datetime
#  photoalbum_id        :integer
#  permalink            :string(255)
#

class Picture < ActiveRecord::Base
  include PaperclipHelper

  attr_protected :picture_file_name, :picture_content_type, :picture_file_size
  belongs_to :author, :class_name => "User"
  belongs_to :photoalbum
  has_permalink :title
  
  
  has_many :comments, :as => :commentable, :order => 'created_at DESC', :dependent => :destroy
  acts_as_taggable_on :tags
  
  # Paperclip 
  has_attached_file :picture, { :styles => {:picture => "600x", :preview => "166x100#", :thumbnail => "100x75>"} }.merge(PAPERCLIP_OPTIONS)

  validates_attachment_content_type :picture, :content_type => IMAGE_MIME_TYPES,
                                              :if => :has_picture?,
                                              :message => 'Picture should be a jpeg, gif or png.'
  
  validates_attachment_presence :picture, :message => 'Please upload an image.'                                       

  # Validations
  validates :title, :presence => true, :uniqueness => true
  validates :author, :presence => true
  validates :photoalbum, :presence => true
  validates :published_on, :presence => true
  
  def to_param
    permalink
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::AdminController
  
  def index
    @pictures = Picture.all(:order => 'published_on DESC')
  end
  
  def show
    @picture = Picture.find_by_id(params[:id])
  end
  
  def new
    @picture = Picture.new
  end
  
  def create
    @picture = Picture.new(params[:picture])
    if @picture.save
      flash[:notice] = "Picture successfully created."
      redirect_to admin_picture_path(@picture)
    else
      flash[:error] = "Picture was not created. Please check the errors"
      render :new
    end
  end
  
  def edit
    @picture = Picture.find_by_id(params[:id])
  end
  
  def update
    @picture = Picture.find(params[:id])
    @picture.update_attributes(params[:picture])
    if @picture.save
      flash[:notice] = "Picture successfully updated."
      redirect_to admin_picture_path(@picture)
    else
      flash[:error] = "Picture was not updated. Please check the errors."
      render :edit
    end
  end
  
  def destroy
    @picture = Picture.find(params[:id])
    
    @picture.destroy()
    flash[:notice] = "Picture successfully removed."
    redirect_to admin_pictures_path
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :fetch_photoalbum
  
  PICTURES_PER_PAGE = 20
  
  def show
    @picture = @photoalbum.pictures.find_by_permalink(params[:id])
  end
  
  def tagged
    @tag = Tag.find_by_name(params[:tag])
    @tagged_pictures = @photoalbum.pictures.tagged_with(params[:tag], :on => :tags).paginate(:page => params[:page], :per_page => PICTURES_PER_PAGE)
  end
  
  private
  
  def fetch_photoalbum
    @photoalbum = Photoalbum.find_by_permalink(params[:photoalbum_id])
  end
end

app/views/pictures/_comment.html.erb
<div class="comment">
	<div class='avatar'>
    <% if comment.author.has_avatar? %>
      <%= image_tag comment.author.avatar.url(:avatar), :alt => comment.author.username %>
    <% else %>
      <%= image_tag 'blank_avatar.gif', :alt => comment.author.username %>
    <% end %>
  </div>
	<p>Posted by: <%= comment.author.username %> on <%= comment_published_on_text(comment) %></p>
	<p><%= comment.body %></p>
	<p><%= link_to "Delete", comment_path(comment), :method => :delete %>
</div>

app/views/pictures/_picture.html.erb
<li class="picture_mini">
  <%= image_tag picture.picture.url(:preview), :alt => picture.title %>
  <h2><%= link_to picture.title, photoalbum_picture_path(@photoalbum, picture) %></h2>
</li>

app/views/pictures/show.html.erb
<%= link_to "Back", :back, :class => 'back_link' %>
<h1><%= @picture.title %></h1>

  
<div class="full_picture_display"><%= image_tag @picture.picture.url(:picture), :alt => @picture.title %></div>
<p class="author">Posted by <span><%= @picture.author.username %></span> on <span><%= published_on_text(@picture) %></span></p>
<p class="description"><%= @picture.description %></p>
<% unless @picture.tags.empty? %>
  <p class="tags">
    <span class="tag_label">Tagged with:</span> 
    <% @picture.tags.each do |t| %>
      <%= link_to t.name, {:tag => t.name, :action => :tagged, :controller => :pictures} %>
    <% end %>
  </p>
<% end %>

<div class="comments">
  <%= link_to "Add Comment", new_picture_comment_path(@picture) unless current_user.nil? %>
  
  <%= render :partial => 'comments/comment', :collection => @picture.comments %>
</div>