config/routes.rb
AndrewMitchell::Application.routes.draw do
  namespace :admin do resources :employment_history_items end

  namespace :admin do resources :educational_qualifications end

  namespace :admin do resources :categories end

  namespace :admin do resources :posts end

  namespace :admin do root :to => 'dashboard#index' end

  post        '/auth/:provider/callback'              => 'authentications#create'
  get         '/profile/connected-providers'          => 'authentications#index', :as => 'authentications'
  delete      '/profile/connected-provider/:provider' => 'authentications#destroy', :as => 'authentication'

  devise_for  :users, :controllers => { :registrations => 'registrations' }
  resources   :users


  ### FRONTEND ###

  # Static Pages
  get         '/contact'  => 'static_pages#contact'

  # About
  get         '/about'                      => 'about#index'
  get         '/employment-history'         => 'about#employment_history',          :as => 'employment_history'
  get         '/educational-qualifications' => 'about#educational_qualifications',  :as => 'educational_qualifications'

  # Comments
  resources   :comments

  # Posts
  resources   :posts, :only => [:show] do
    resources   :comments, :except => [:delete]
  end
  get         'posts/category/:category_permalink'  => 'posts#category', :as => 'posts_category'
  get         'posts/tagged/:tag'                   => 'posts#tagged'

  # Portfolio
  get '/portfolio' => 'portfolio#index'
  get '/portfolio/:id' => 'portfolio#show'
  #   resources :comments, :except => [:delete]
  # end
  # match 'portfolio/category/:category_permalink' => 'portfolio#category', :as => 'portfolio_category'
  # match 'portfolio/tagged/:tag' => 'portfolio#tagged'

  # Photos & Albums
  resources :photoalbums, :only => [:index, :show] do
    resources :pictures, :only => [:show] do
      resources :comments, :except => [:delete]
    end
  end
  match 'pictures/tagged/:tag' => 'pictures#tagged'

  root :to => "posts#index"
end

app/models/photoalbum.rb
# == Schema Information
#
# Table name: photoalbums
#
#  id           :integer         not null, primary key
#  author_id    :integer
#  name         :string(255)
#  description  :text
#  published_on :datetime
#  created_at   :datetime
#  updated_at   :datetime
#  permalink    :string(255)
#

class Photoalbum < ActiveRecord::Base
  belongs_to      :author,          :class_name => "User"
  has_many        :pictures
  has_permalink   :name
  
  
  # Validations
  validates       :name,            :presence => true, :uniqueness => true
  validates       :description,     :presence => true
  validates       :author,          :presence => true
  validates       :published_on,    :presence => true
  
  # Delegations
  
  # Methods
  
  def display_item
    pictures.first
  end

  def to_param
    permalink
  end
end

app/controllers/photoalbums_controller.rb
class PhotoalbumsController < ApplicationController
  
  ALBUMS_PER_PAGE = 20
  
  def index
    @photoalbums = Photoalbum.order('published_on DESC').paginate(:page => params[:page], :per_page => ALBUMS_PER_PAGE)
  end
  
  def show
    @photoalbum = Photoalbum.find_by_permalink(params[:id])
    @pictures = @photoalbum.pictures.order('published_on DESC').paginate(:page => params[:page], :per_page => ALBUMS_PER_PAGE)
  end
end

app/views/admin/photoalbums/_photoalbum.html.erb
<div class="picture">
  <h3><%= link_to picture.title, picture_path(picture) %></h3>
  <div class="mini_picture_display">
    <%= image_tag picture.picture.url(:thumbnail), :alt => picture.title %>
  </div>
  <p class="author">Posted by <span><%= picture.author.username %></span> on <span><%= published_on_text(picture) %></span></p>
  <p class="body"><%= picture.description %></p>
</div>

app/views/admin/photoalbums/_picture.html.erb
<div class="comment">
  <div class='avatar'>
    <% if comment.author.has_avatar? %>
      <%= image_tag comment.author.avatar.url(:avatar), :alt => comment.author.username %>
    <% else %>
      <%= image_tag 'blank_avatar.gif', :alt => comment.author.username %>
    <% end %>
  </div>
  <p>Posted by: <%= comment.author.username %> on <%= comment_published_on_text(comment) %></p>
  <p><%= comment.body %></p>
  <p><%= link_to "Delete", comment_path(comment), :method => :delete %>
</div>

app/views/admin/photoalbums/index.html.erb
<div id="pictures_page">
	<div class="title_block clearfix">
		<h2>Pictures</h2>
	</div>
	<%= render :partial => 'shared/flash_messages' %>
	
	<% if @pictures.empty? %>
		<p>There are currently no pictures.</p>
	<% else %>
		<%= render :partial => 'picture', :collection => @pictures %>
	<% end %>
	
	<%= will_paginate %>
</div>

app/views/admin/photoalbums/show.html.erb
<div id="picture_page">
	<div class="title_block clearfix">
		<h2>Picture - <%= @picture.title %></h2>
	</div>
	
	<%= render :partial => 'shared/flash_messages' %>
	
	
	<div class="full_picture_display"><%= image_tag @picture.picture.url(:picture), :alt => @picture.title %></div>
	<p class="author">Posted by <span><%= @picture.author.username %></span> on <span><%= published_on_text(@picture) %></span></p>
	<p class="description"><%= @picture.description %></p>
	<% unless @picture.tags.empty? %>
		<p class="tags">
			<span class="tag_label">Tagged with:</span> 
			<% @picture.tags.each do |t| %>
				<%= link_to t.name, {:tag => t.name, :action => :tagged, :controller => :pictures} %>
			<% end %>
		</p>
	<% end %>
	
	<div class="comments">
		<%= link_to "Add Comment", new_picture_comment_path(@picture) unless current_user.nil? %>

		<%= render :partial => 'shared/comment', :collection => @picture.comments %>
	</div>
</div>